apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-task-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: celestiv/neoflex_demo_app
        name: kubernetes-task-deployment
        ports:
          - containerPort: 8080
